### ISSUE TITLE
Info page links are broken when running behind a proxy.

### ISSUE THREAD

**Issue by aleks-m** [caarlos0/domain_exporter#159]
Hi.

I am trying to run this exporter behind a proxy. And links on the info page appear to be broken, e.g.:

Running on http://monitoring.foobar.com/domain_exporter
/metrics link looks like http://monitoring.foobar.com/metrics
but should be intstead:
http://monitoring.foobar.com/domain_exporter/metrics

At the same time blackbox exporter works fine.
From a page source I see what there is a difference in how links are generated in blackbox exporter and domain exporter:

```
<html>
    <head><title>Blackbox Exporter</title></head>
    <body>
    <h1>Blackbox Exporter</h1>
    <p><a href="probe?target=prometheus.io&module=http_2xx">Probe prometheus.io for http_2xx</a></p>
    <p><a href="probe?target=prometheus.io&module=http_2xx&debug=true">Debug probe prometheus.io for http_2xx</a></p>
    <p><a href="metrics">Metrics</a></p>
    <p><a href="config">Configuration</a></p>
    <h2>Recent Probes</h2>
```

```
      <html>
      <head><title>Domain Exporter</title></head>
      <body>
        <h1>Domain Exporter</h1>
        <p><a href="/metrics">Metrics</a></p>
        <p><a href="/probe?target=google.com">probe google.com</a></p>
      </body>
      </html>
```

Note `metrics` vs `/metrics`. So probably just removing that slash will work...

**Comment by caarlos0** [comment]
ah, you can actually just set `DOMAIN_EXPORTER_URL_PREFIX=http://monitoring.foobar.com/domain_exporter`, so, no need to change anything really
