### ISSUE TITLE
[Docs] Update "--config" information

### ISSUE THREAD

**Issue by timmay54** [caarlos0/domain_exporter#168]
When using docker compose, the documentation didn't explicitly state information for docker & docker compose, as well as the note that when trying to use the "--config" parameter, an equal sign must be used to set the variable. 

If the docs explained something like "when using docker / docker compose, you will use `--config=/domains.yaml` and you can add this parameter in your compose file by adding the "commands:" section.

**Comment by caarlos0** [comment]
That's more how docker/docker-compose arg-parsing works than how to use domain_exporter itself.

Nevertheless, improved docs a little bit.
