### ISSUE TITLE
[Docs] Add Example Grafana Dashboard ID / Json

### ISSUE THREAD

**Issue by timmay54** [caarlos0/domain_exporter#169]
When searching for a default dashboard to get jumpstarted for this exporter, I only see 2 outdated Grafana dashboards:

- https://grafana.com/grafana/dashboards/13924-9116-domain/ (not anything related)
- https://grafana.com/grafana/dashboards/14605-domain-exporter-for-prometheus/ (close, but does not work out of the box)

Either adding a dashboard & maintaining it on Grafana's community page OR adding the dashboard json to this repo would enable users to clone this repo and get started much faster

**Comment by caarlos0** [comment]
maybe someone can share their dashboard.json?

**Comment by pavo976** [comment]
- https://github.com/zifter/helm-charts/blob/main/charts/domain-exporter/dashboards/domain-expiration-overview.json

**Comment by caarlos0** [comment]
thanks @pavo976


will close the issue
