### ISSUE TITLE
.in and .co domains not working

### ISSUE THREAD

**Issue by shib4u** [caarlos0/domain_exporter#190]
Looks like whois requests are going to 103.132.246.21:43.... is this hardcoded anywhere?
Why is this not using linux command "whois" ?
Is it possible to specify a whois host for a specific record?

Logs: Apr 17 16:29:44 monitoring domain_exporter[643854]: 4:29PM ERR failed to probe {techpartner.in } error="failed to fetch whois request: read tcp 172.30.10.xxx:4:43874->103.132.246.21:43: read: connection reset by peer"
Apr 17 16:33:49 monitoring domain_exporter[643854]: net.Error timeout=false, temp=false: read tcp 172.30.10.xxx:48578->52.4.69.60:43: read: connection reset by peer

**Comment by caarlos0** [comment]
> Looks like whois requests are going to 103.132.246.21:43.... is this hardcoded anywhere?

not on domain_exporter

> Why is this not using linux command "whois" ?

because it does the whois queries directly

> Is it possible to specify a whois host for a specific record?

yes, check readme
