### ISSUE TITLE
linux/arm64 images missing

### ISSUE THREAD

**Issue by filipc** [caarlos0/domain_exporter#204]
I kindly ask to add docker `linux/arm64` versions of the image

**Comment by caarlos0** [comment]
https://hub.docker.com/layers/caarlos0/domain_exporter/latest/images/sha256-abfaed8f8d07ded04292dc1b45639a040726bc9ce9de8f7ce3668ade75051103?context=explore 


it already exists...

**Comment by filipc** [comment]
Yeah, sorry, I meant `linux/arm/v8` is missing.
I'm trying to pull it from Raspbian 11 / Raspberry Pi OS.
