### ISSUE TITLE
There's no way to add labels to individual domains

### ISSUE THREAD

**Issue by maintain3r** [caarlos0/domain_exporter#210]
Hello maintainer,
Would it be possible to add labels to domain names?
That would help a lot for cases where different domains names are governed by different teams, or some domains are under specific registrars, etc.

domains:
- name: reddit.com
  host: whois.godaddy.com
  labels:
  - label1: value1
  - label1L value2

Thanks

**Comment by caarlos0** [comment]
use metric relabelings in your prometheus config
