### ISSUE TITLE
tld's not parsing correctly

### ISSUE THREAD

**Issue by ZyanKLee** [caarlos0/domain_exporter#23]
I found some TLDs that have problems matching and parsing the expiry date. To help with debugging I wrote up a list of expiry date entries:

```
.sk: 
Valid Until:                  2020-09-08

.ro:
Expires On: 2021-09-18

.cz:
expire:       14.03.2020

.pt:
Data de expiração / Expiration Date (dd/mm/yyyy): 02/11/2019

.it:
Expire Date:        2019-08-06
```

**Comment by caarlos0** [comment]
awesome, thanks!

**Comment by caarlos0** [comment]
do you have some domain samples for me to try?

**Comment by ZyanKLee** [comment]
I personally had the trouble parsing kaiserkraft.$tld, additionally you might have a look at amazon.$tld (apparently no .sk entry) and google.$tld?
