### ISSUE TITLE
validation for .co.kr 

### ISSUE THREAD

**Issue by Ravikanthreddy** [caarlos0/domain_exporter#25]
Is it possible to cover the validation for this domains.
ex: google.co.kr
Expiry Date format:  2020. 07. 28

**Comment by Ravikanthreddy** [comment]
also 'com.tr'
format: 2020-Oct-22

**Comment by caarlos0** [comment]
sure, feel free to open a PR as well :)

**Comment by it-toppp** [comment]
and co.il, pp.ua

**Comment by caarlos0** [comment]
.kr was done on #64
