### ISSUE TITLE
Parameter host for whois server does not work enough

### ISSUE THREAD

**Issue by katylys** [caarlos0/domain_exporter#284]
hello, I have trouble with nigerian domains. I can't to catch expiration days, I thought that i should to use whois server of Nigeria, but it's not working. Could you help please, if you know how it could be fixed?

Domain-exporter is in kubernetes, version of domain-exporter docker.io/caarlos0/domain_exporter:v1.23.0

Error from domain-exporter

`4:12PM ERR failed to probe {immigration.gov.ng whois.nic.net.ng} error="could not parse whois response: \"Your request could not be performed. Lookup quota exceeded.\""`

`whois immigration.gov.ng
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.nic.net.ng

domain:       NG`

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/e3f95f28-287e-4cb8-994b-58c25dc8a4a1">

**Comment by caarlos0** [comment]
> Your request could not be performed. Lookup quota exceeded

you are querying the servers too much, apparently.
