### ISSUE TITLE
domain_exporter can't resolve German TLD domains (".de")

### ISSUE THREAD

**Issue by fhemberger** [caarlos0/domain_exporter#4]
`https://domainr.com/google.de?q=google.de` works, but the same query with domain_exporter
(`http://localhost:9222/probe?target=google.de`) results in error "couldnt parse whois for domain: google.de"

**Comment by caarlos0** [comment]
`whois google.de` and `whois facebook.de` don't show any form of expiration date, that's why it doesn't work...

is this a "germany thing"?  don't know if I can do anything about this...

**Comment by fhemberger** [comment]
DeNIC's whois format is a bit different and is about to change even more (along with probably all other European NICs), when the new EU data protection regulations take effect in May.

**Comment by caarlos0** [comment]
still no expiration date.

wontfix I guess 🤷‍♂️
