### ISSUE TITLE
dial tcp: lookup domain on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by PinGwynn** [caarlos0/domain_exporter#6]
Hello,

I've tried to use yours exporter inside the docker under docker-compose, but it returns the same answer for all domains.
Like:
Get http://domain:9222/probe?target=watchub.pw: dial tcp: lookup domain on 127.0.0.11:53: no such host

Also, I've ran ping comand inside the container, and domain name resolves fine.

Could you advice, what I do wrong ? And domain can be registered but don't contain any DNS records.

Thank you.

**Comment by caarlos0** [comment]
weird, works just fine here:

```
$ curl http://localhost:9222/probe?target=watchub.pw
# HELP domain_expiry_days time in days until the domain expires
# TYPE domain_expiry_days gauge
domain_expiry_days 197
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 1.305136056
```

**Comment by PinGwynn** [comment]
Thank you very much. It was my docker-compose misconfiguration

**Comment by caarlos0** [comment]
@PinGwynn hey, just curious, what was misconfigured?

**Comment by PinGwynn** [comment]
I've used container_name in prometheus config instead of the service name.

**Comment by caarlos0** [comment]
Oh, thanks, I was having the same problem in a different service haha

Thaks 😬

**Comment by vakafonic** [comment]
I have same issue using vagrant local site with turned on VPN in chrome browser extension.
If you do so - finish VPN connection and try to access page

**Comment by KEHSIHBA-IGAYT** [comment]
> Thank you very much. It was my docker-compose misconfiguration

Could you please help me with the correct configuration as I am stuck with the same error while setting up the hyperledger fabric network?

**Comment by SergyKor** [comment]
turn off VPN

**Comment by charlesdeb** [comment]
I wasn't using domain_exporter, but my google searches brought me here, so they may bring someone else here as well.

The reason why I was getting no host and dial tcp errors was that my docker-compose.yml file had some old extra (and unnecessary) network configuration in it. Once I deleted all of it, then the host name resolved fine and all worked well (between a PHP container and a mailhog container)

**Comment by da-edra** [comment]
I keep getting this problem, my docker-compose.yml doesn't have any errors and I'm not using a VPN at the moment, what could be causing this problem?
